[project]
name = "crank-yanker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
pythonpath = "."